name: 3DInfomax
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - rdkit
  - pytorch-geometric
  - dgl-cuda10.2
  - pot
  - numpy
  - certifi
  - ogb
